version: "3.8"

services:
  # Banco Vetorial ChromaDB (Escalonável Client/Server)
  chromadb:
    image: chromadb/chroma:latest
    container_name: ser-aluno-chromadb
    ports:
      - "8002:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - chroma_db_data:/chroma/chroma
    networks:
      - mock-network

  agent-api:
    build: .
    container_name: agent-api
    command: uvicorn agent_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - MCP_URL=${MCP_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - REALM=${REALM}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DEV_MODE=${DEV_MODE}
      - DB_PATH=/app/data/aluno_memory.db
    networks:
      - mock-network
    volumes:
      - agent_api_sqlite:/app/data
    depends_on:
      - chromadb

  streamlit-ui:
    build: .
    container_name: streamlit-ui
    command: streamlit run app_streamlit.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://agent-api:8000
    networks:
      - mock-network
    depends_on:
      - agent-api

networks:
  mock-network:
    driver: bridge

volumes:
  chroma_db_data:
  agent_api_sqlite:
