#!/usr/bin/expect -f
set timeout 120
set host "192.168.40.33"
set port "2222"
set user "biserdados"
set password "YLU3HZKXN5LPZLQZALU3"

spawn ssh -o StrictHostKeyChecking=no -p $port $user@$host
expect {
    "yes/no" { send "yes\r"; exp_continue }
    "password:" { send "$password\r" }
}

expect "*$ "
send "echo $password | sudo -S docker logs agent-api --tail 100\r"
expect "*$ "
send "exit\r"
expect eof
