#!/usr/bin/expect -f
set timeout 60
set host "192.168.40.33"
set port "2222"
set user "biserdados"
set password "YLU3HZKXN5LPZLQZALU3"

spawn ssh -o StrictHostKeyChecking=no -p $port $user@$host
expect {
    "password:" { send "$password\r" }
}
expect "*$ "
send "ping -c 2 keycloak.aws-dev.sereducacional.com\r"
expect "*$ "
send "curl -v https://keycloak.aws-dev.sereducacional.com/health/ready\r"
expect "*$ "
send "exit\r"
expect eof
